# Generated by Django 4.2.3 on 2024-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishApp', '0003_ingredient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'ingrédient"),
        ),
    ]
